### PR TITLE
make some fixes & tests for container-injections

### PR DESCRIPTION
**Pull request by acburdine**

### CODE REVIEW

**Comment by acburdine** [comment]
@davewasmer I took a stab at making the request class implement the readable stream - gonna test with my app locally as well to see if it works

**Comment by acburdine** [comment]
Ok, so I figured out a way to make the Request class work correctly with middleware....essentially it does the same thing as the Model class where it returns a proxy. If it's looking for a function that exists on the IncomingMessage object, it returns that function, otherwise it defaults to the model. It seems, however, that this is probably a _huge_ hack and not great for performance. Any other suggestions?

**Comment by davewasmer** [comment]
@acburdine the reason we use Proxies for models is because we want to allow arbitrary property & method lookups at runtime that delegate to the underlying ORM instance. Essentially we want a `method_missing` from Ruby. This is necessary because different ORMs will expose different APIs, so we can't know ahead of time what methods/properties to delegate.

The Request class, on the other hand, only has to mimic Express' `req` object, which has a known, limited surface area. Therefore, theoretically, we should be able to create individual getter/setter methods for each item on the `req` interface, allowing us to skip the Proxy complexity.

Is there some aspect of `req` in particular that is difficult to wrap?

**Comment by acburdine** [comment]
Yeah - Express's `req` object actually _extends_ http.IncomingMessage, which is what makes it so difficult to wrap. IncomingMessage itself implements the Readable interface, which also implements EventEmitter. Essentially you have those two interfaces that Denali's Request class must also implement 😕. In this PR I took a stab at making the Request class implement Readable, but that didn't work when I tried to use it.

Alternatively, we could take the same approach that Express does and have the request class extend IncomingMessage - it currently extends DenaliObject but I can't think of any case where the Request needs to have container access?

**Comment by acburdine** [comment]
Ok, so I got the new methods implemented, and I'm running the full suite now to make sure the coverage is 100% for the Request class

**Comment by acburdine** [comment]
After running tests, here's the new coverage for the request class: 
screen shot 2017-05-11 at 2 28 22 pm

**Pull request merged**
