### PR TITLE
Test attribute setting on model

### PR DESCRIPTION
**Pull request by knownasilya**
wip, don't merge

### CODE REVIEW

**Comment by davewasmer** [comment]
Is this still in progress, or is it okay to close @knownasilya?

**Comment by knownasilya** [comment]
I think you can merge this.

**Comment by davewasmer** [comment]
This test feels a little over broad for a unit test. I think we probably want to test that the Model class invokes setAttribute on the adapter (by stubbing out an adapter), rather than tying this test to the MemoryAdapter implementation.

**Comment by knownasilya** [comment]
Ah, yes good point.

**Comment by davewasmer** [comment]
Closing for lack of activity. Happy to reopen if anyone wants to pick up the ball here - more tests are always welcome!

**Pull request closed without merging**
