### PR TITLE
docs: Mention typescript install for getting started

### PR DESCRIPTION
**Pull request by knownasilya**

### CODE REVIEW

**Comment by knownasilya** [comment]
It's necessary, because you have a peerDependency.

**Comment by davewasmer** [comment]
Hm, that's odd - Denali's package.json doesn't list any peerDeps. Could you paste the entire output where you see the failure?

**Comment by knownasilya** [comment]
screen shot 2017-03-01 at 8 57 01 am

**Comment by davewasmer** [comment]
Looks like it was a peerDep of `broccoli-typescript-compiler`, which was incorrectly marked as a full dep rather than a devDep.

I'm going through and pruning the deps locally, plus marking any devDeps that aren't marked as such, which should fix this.

**Pull request closed without merging**
