### PR TITLE
[WIP] Allow addons to modify builds, and extract out standard build steps

### PR DESCRIPTION
**Pull request by davewasmer**
## Overview

This PR introduces new APIs for the Builder class, used in the `denali-build.js` file. Specifically, it adds support for `processSelf()`, `processEach()`, `processParent()`, and `processApp()`. These hooks allow users to customize the build process for an app or it's addons:

* `processSelf()` is invoked with broccoli tree of the addon or app that it appears in
* `processEach()` is invoked with the broccoli tree of the consuming app, as well as all other addons in the consuming app's dependencies
* `processParent()` is invoked with the broccoli tree of the parent node: either the consuming app (if it appears in a top level addon) or the consuming addon (if it appears as a nested dependency of an addon)
* `processApp()` is invoked with the broccoli tree of the consuming app, no matter how deeply nested it appears in the dependency graph

As an example, the standard build process (transpile via babel, run eslint) was extracted into `denali-babel` and `denali-eslint`. Now, the only build steps baked into core are the basic ones required to create the compiled app structure Denali needs.

## Caveats

A consequence of this extraction of the standard build process into addons is the introduction of cycles in Denali's dependencies. Denali now depends on `denali-babel`, which depends in turn on `denali`, which depends on `denali-babel`, and so on. npm3+ and yarn have no trouble installing these, but it does introduce a complication:

`denali-babel` and `denali-eslint`, the two dependencies that introduce cycles, must have their own denali version bumped in lockstep (or at least compatible with) with denali itself. If the latest`denali-babel` depends on `denali@1.0.0`, and you attempt to scaffold a new app with `denali@2.0.0`, the following dependency tree will be created:

```
my-app
  -> denali@2.0.0
    -> denali-babel@1.0.0
      -> denali@1.0.0
```

This will result in Denali compiling and using two separate instances of Denali at build and runtime. But as long as the version ranges are compatible, and bumped in lockstep when not, npm3 and yarn will flatten the dependency tree, and Denali will only be included once and build and runtime:

```
my-app
  -> denali@1.5.0
    -> denali-babel@1.x.x (depends on denali@1.x.x, the top-level denali satisfies the dependency, so no nested second install)
```

### Alternatives

We could inline the build steps that `denali-babel` and `denali-eslint` perform into Denali's own `denali-build.js`, while leaving those addons in the default blueprint for apps. This would avoid cyclical dependencies in Denali itself, but means that we won't be dogfooding the babel or eslint addons.

## Conclusions

I'm inclined to take the alternative approach. It would keep all the benefits for other addons (i.e. denali-mailer would now be able to compile mailer templates everywhere), but avoids the complexities of managing denali-babel and denali-eslint versions. It was useful to build it out this way to ensure the Denali could handle cyclical addons (it's possible userland addons might have cycles), but now that it's proven out, it might not be worth the maintenance headache.

Or perhaps I'm missing a third way that avoids all these problems. Thoughts?

### CODE REVIEW

**Comment by knownasilya** [comment]
Also, there is this issue https://github.com/denali-js/denali-eslint/issues/1, but it would remain either way I think.

**Comment by davewasmer** [comment]
Hm, I'm now realizing the problems that result from the cyclical dependencies will happen even without denali's own cycles.

If `my-app` depends on `denali-my-addon`, which depends on `denali`, it's possible (likely, even) that `denali-my-addon` depends on a different version of `denali` than `my-app`:

```
my-app
-> denali@1.0.0
->  denali-my-addon@3.2.1
  ->  denali@1.0.1
```

This would result in denali loading twice at runtime, the same problem the cycles caused.

However, I think there might be a solution that gets us the best of all worlds here: addons depend on `denali` as a devDependency.

When Denali builds the addon graph, it only searches package dependencies, not devDependencies. So if addon's included denali in their devDependency, they wouldn't be surreptitiously injecting a separate version of denali at runtime (since it wouldn't be picked up as an addon). It also would solve the cycle problem: Denali could depend on denali-babel. It would still technically cause a cycle (assuming you don't `npm install --production` every time), but the cycle would be ignored by denali.

Investigating this option now ...

**Comment by davewasmer** [comment]
More brain dump:

Moving denali into devdeps introduces new problems.

Assume I have an app that uses denali 2.0.0, and I try to install an addon that is built against 1.0.0, and my deployment scripts run `npm install --production` when installing dependencies in prod:

```
my-app
-> denali@2.0.0
-> my-addon@1.0.0
  -> denali@1.0.0
```

If denali is listed as a devdep on `my-addon`, that means denali 1.0.0 won't be installed in prod. When `my-addon` imports denali, it'll get 2.0.0 instead. So using devdeps as a way to avoid cycles is out.

**Comment by davewasmer** [comment]
Rehashing some of the problem constraints here, off the top of my head:

* Addons should not need the exact same version of a shared addon dependency as the consuming app.
* Addons (including Denali itself), if appearing twice in the dependency graph, should not be auto-loaded into the runtime container twice.

I see a couple potential solutions at the moment:

### Shallow load at runtime

Only load the first level of addons at runtime. Nested addons aren't autoloaded into the container.

If a second level addon needed to be included at runtime (i.e. `denali-drip-emails` depends on `denali-mailer` and needs it at runtime), the first level addon (`denali-drip-emails` in this case) could require it as a peer dependency. 

So the only case unsupported would be an addon nested 3+ levels deep that's needed at runtime. I can't think of any examples of this off the top of my head, and if the Ember ecosystem is any guide, nesting addons 3+ levels deep is likely a rare event.

### Explicit build time config

We could add some configuration API, perhaps some properties to the Builder class you define in `denali-build.js`. Something like:

```
export default class MyAddonBuilder extends Builder {

  buildTimeOnlyAddons: [ 'my-nested-addon' ]

}
```

Thus, if `denali-drip-emails` wants to include `denali-mailer` for it's precompilation of templates, but doesn't want to assume anything about the consuming app's version of denali-mailer, it can add it to the `buildTimeOnlyAddons` array (bikeshedding needed on that property name).

------

Personally, I'm leaning towards shallow addon loading. It reduces API surface area and complexity, satisfies the 95% use case, and the remaining use cases not covered (i.e. use an addon nested 3+ levels deep at runtime) can be solved with manual workarounds (i.e. user installs `addon-with-deep-nesting`, and the project's Readme mentions "oh by the way, install `deeply-nested-addon` too".

I've updated this PR with a sample of the shallow approach, but I'd love to get thoughts.

**Comment by acorncom** [comment]
> Personally, I'm leaning towards shallow addon loading. It reduces API surface area and complexity, satisfies the 95% use case

This sounds responsible to me. At this stage in the game it's probably worth using energy in other places rather than trying to get three levels of loading automatically happening without bugs. If/when Denali has become the defacto Node framework it seems like a problem that could be revisited (if needed) with far clearer use cases :grinning:

**Pull request merged**
