### PR TITLE
feat(cli): print-slow-trees flag for several commands

### PR DESCRIPTION
**Pull request by knownasilya**

### CODE REVIEW

**Comment by acorncom** [comment]
Hmm, we've got a failing test here due to a test timeout.  @davewasmer what's the magic incantation you used to get things to pass last time? 😀

**Comment by davewasmer** [comment]
Try a rebase?

**Comment by knownasilya** [comment]
Worked 👍 just need a review and merge.

**Comment by davewasmer** [comment]
Thanks @knownasilya! :beers:

**Pull request merged**
