### PR TITLE
Add Parsers

### PR DESCRIPTION
**Pull request by davewasmer**
See #277

cc @acburdine @knownasilya @acorncom 

I'd love to get some extra eyes on this and feedback on the API changes.

### CODE REVIEW

**Comment by knownasilya** [comment]
This looks nice. I'll give it a whirl later this week.

**Comment by davewasmer** [comment]
The test failures here are the result of changes to the Action API, and the tests need to be updated to handle parsers (and expanded to test them as well). However, I'm holding off on this until the container refactor settles, since once that lands we should be able to shake out some unit test helpers, which in turn will mean refactoring these Action tests.

**Comment by knownasilya** [comment]
What's the progress on this?

**Comment by davewasmer** [comment]
Holding on this until the container PR lands/settles. The past few weeks have been a bit demanding of my time, so I haven't had much (read: any) spare time to devote here, but fear not, I haven't disappeared for good.

Comments and thoughts on the container PR are more than welcome - they will likely help it land faster _hint hint_.

**Comment by acburdine** [comment]
Do we still need this PR or is it okay to close since the relevant changes are on the `container-injections` branch?

**Comment by davewasmer** [comment]
Yes, we can close - the container injections branch has this change.

**Pull request closed without merging**
