### PR TITLE
fix(cli): let requires 'use strict' otherwise errors

### PR DESCRIPTION
**Pull request by knownasilya**
`denali -h` didn't work, erroring with the let error.

### CODE REVIEW

**Comment by davewasmer** [comment]
Are you using node 6? I'm not getting any errors, and `node -e "let foo = true;"` works fine.

**Comment by knownasilya** [comment]
Checking..

**Comment by davewasmer** [comment]
Perhaps we should do some strict checking, and error out with an intelligent error message, when running in Node < 6

**Comment by knownasilya** [comment]
FYI a node check is impossible in this situation because because node does a syntax check before it runs any code, so it skips over any checks and errors on the let issue.

**Comment by knownasilya** [comment]
Nvm, it's possible if you split it into multiple files.

**Pull request closed without merging**
